//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DataModel", "FK_fds01_hh15", "hh15", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataModel.Contragent), "fds01", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataModel.Doc), true)]
[assembly: EdmRelationshipAttribute("DataModel", "FK_fss011_fds01", "fds01", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataModel.Doc), "fss011", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataModel.DocRecord), true)]
[assembly: EdmRelationshipAttribute("DataModel", "FK_fds0111_fds0111", "fds0111", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataModel.DocRecordPhase), "fds01111", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataModel.DocRecordPhase), true)]
[assembly: EdmRelationshipAttribute("DataModel", "FK_fds0111_fss011", "fss011", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataModel.DocRecord), "fds0111", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataModel.DocRecordPhase), true)]
[assembly: EdmRelationshipAttribute("DataModel", "FK_fds0111_hh15", "hh15", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataModel.Contragent), "fds0111", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataModel.DocRecordPhase), true)]
[assembly: EdmRelationshipAttribute("DataModel", "FK_fss011_fss011", "fss011", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataModel.DocRecord), "fss0111", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataModel.DocRecord), true)]
[assembly: EdmRelationshipAttribute("DataModel", "FK_fss011_hh07", "hh07", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataModel.Employee), "fss011", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataModel.DocRecord), true)]
[assembly: EdmRelationshipAttribute("DataModel", "FK_fss011_hh15", "hh15", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataModel.Contragent), "fss011", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataModel.DocRecord), true)]
[assembly: EdmRelationshipAttribute("DataModel", "FK_hh07_hh15", "hh15", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataModel.Contragent), "hh07", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataModel.Employee), true)]
[assembly: EdmRelationshipAttribute("DataModel", "FK_fds01_hh07", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataModel.Employee), "fds01", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataModel.Doc), true)]

#endregion

namespace DataModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DataModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DataModelContainer object using the connection string found in the 'DataModelContainer' section of the application configuration file.
        /// </summary>
        public DataModelContainer() : base("name=DataModelContainer", "DataModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataModelContainer object.
        /// </summary>
        public DataModelContainer(string connectionString) : base(connectionString, "DataModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataModelContainer object.
        /// </summary>
        public DataModelContainer(EntityConnection connection) : base(connection, "DataModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Doc> Docs
        {
            get
            {
                if ((_Docs == null))
                {
                    _Docs = base.CreateObjectSet<Doc>("Docs");
                }
                return _Docs;
            }
        }
        private ObjectSet<Doc> _Docs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DocRecordPhase> DocRecordPhases
        {
            get
            {
                if ((_DocRecordPhases == null))
                {
                    _DocRecordPhases = base.CreateObjectSet<DocRecordPhase>("DocRecordPhases");
                }
                return _DocRecordPhases;
            }
        }
        private ObjectSet<DocRecordPhase> _DocRecordPhases;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DocRecord> DocRecords
        {
            get
            {
                if ((_DocRecords == null))
                {
                    _DocRecords = base.CreateObjectSet<DocRecord>("DocRecords");
                }
                return _DocRecords;
            }
        }
        private ObjectSet<DocRecord> _DocRecords;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> Employes
        {
            get
            {
                if ((_Employes == null))
                {
                    _Employes = base.CreateObjectSet<Employee>("Employes");
                }
                return _Employes;
            }
        }
        private ObjectSet<Employee> _Employes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Contragent> Contragents
        {
            get
            {
                if ((_Contragents == null))
                {
                    _Contragents = base.CreateObjectSet<Contragent>("Contragents");
                }
                return _Contragents;
            }
        }
        private ObjectSet<Contragent> _Contragents;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Docs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDocs(Doc doc)
        {
            base.AddObject("Docs", doc);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DocRecordPhases EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDocRecordPhases(DocRecordPhase docRecordPhase)
        {
            base.AddObject("DocRecordPhases", docRecordPhase);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DocRecords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDocRecords(DocRecord docRecord)
        {
            base.AddObject("DocRecords", docRecord);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployes(Employee employee)
        {
            base.AddObject("Employes", employee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Contragents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContragents(Contragent contragent)
        {
            base.AddObject("Contragents", contragent);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="Contragent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Contragent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Contragent object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Contragent CreateContragent(global::System.Int32 id)
        {
            Contragent contragent = new Contragent();
            contragent.Id = id;
            return contragent;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_fds01_hh15", "fds01")]
        public EntityCollection<Doc> Docs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Doc>("DataModel.FK_fds01_hh15", "fds01");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Doc>("DataModel.FK_fds01_hh15", "fds01", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_fds0111_hh15", "fds0111")]
        public EntityCollection<DocRecordPhase> RecordPhase
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DocRecordPhase>("DataModel.FK_fds0111_hh15", "fds0111");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DocRecordPhase>("DataModel.FK_fds0111_hh15", "fds0111", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_fss011_hh15", "fss011")]
        public EntityCollection<DocRecord> DocRecords
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DocRecord>("DataModel.FK_fss011_hh15", "fss011");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DocRecord>("DataModel.FK_fss011_hh15", "fss011", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_hh07_hh15", "hh07")]
        public EntityCollection<Employee> Employees
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Employee>("DataModel.FK_hh07_hh15", "hh07");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Employee>("DataModel.FK_hh07_hh15", "hh07", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="Doc")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Doc : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Doc object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="contragentId">Initial value of the ContragentId property.</param>
        public static Doc CreateDoc(global::System.Int32 id, global::System.Int32 contragentId)
        {
            Doc doc = new Doc();
            doc.Id = id;
            doc.ContragentId = contragentId;
            return doc;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ContragentId
        {
            get
            {
                return _ContragentId;
            }
            set
            {
                OnContragentIdChanging(value);
                ReportPropertyChanging("ContragentId");
                _ContragentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContragentId");
                OnContragentIdChanged();
            }
        }
        private global::System.Int32 _ContragentId;
        partial void OnContragentIdChanging(global::System.Int32 value);
        partial void OnContragentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InDocNum
        {
            get
            {
                return _InDocNum;
            }
            set
            {
                OnInDocNumChanging(value);
                ReportPropertyChanging("InDocNum");
                _InDocNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InDocNum");
                OnInDocNumChanged();
            }
        }
        private global::System.String _InDocNum;
        partial void OnInDocNumChanging(global::System.String value);
        partial void OnInDocNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> InDocDate
        {
            get
            {
                return _InDocDate;
            }
            set
            {
                OnInDocDateChanging(value);
                ReportPropertyChanging("InDocDate");
                _InDocDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InDocDate");
                OnInDocDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _InDocDate;
        partial void OnInDocDateChanging(Nullable<global::System.DateTime> value);
        partial void OnInDocDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OutDocNun
        {
            get
            {
                return _OutDocNun;
            }
            set
            {
                OnOutDocNunChanging(value);
                ReportPropertyChanging("OutDocNun");
                _OutDocNun = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OutDocNun");
                OnOutDocNunChanged();
            }
        }
        private global::System.String _OutDocNun;
        partial void OnOutDocNunChanging(global::System.String value);
        partial void OnOutDocNunChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> OutDocDate
        {
            get
            {
                return _OutDocDate;
            }
            set
            {
                OnOutDocDateChanging(value);
                ReportPropertyChanging("OutDocDate");
                _OutDocDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OutDocDate");
                OnOutDocDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _OutDocDate;
        partial void OnOutDocDateChanging(Nullable<global::System.DateTime> value);
        partial void OnOutDocDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EmployeeId
        {
            get
            {
                return _EmployeeId;
            }
            set
            {
                OnEmployeeIdChanging(value);
                ReportPropertyChanging("EmployeeId");
                _EmployeeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmployeeId");
                OnEmployeeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _EmployeeId;
        partial void OnEmployeeIdChanging(Nullable<global::System.Int32> value);
        partial void OnEmployeeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_fds01_hh15", "hh15")]
        public Contragent Contragent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contragent>("DataModel.FK_fds01_hh15", "hh15").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contragent>("DataModel.FK_fds01_hh15", "hh15").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Contragent> ContragentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contragent>("DataModel.FK_fds01_hh15", "hh15");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Contragent>("DataModel.FK_fds01_hh15", "hh15", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_fss011_fds01", "fss011")]
        public EntityCollection<DocRecord> DocRows
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DocRecord>("DataModel.FK_fss011_fds01", "fss011");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DocRecord>("DataModel.FK_fss011_fds01", "fss011", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_fds01_hh07", "Employee")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DataModel.FK_fds01_hh07", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DataModel.FK_fds01_hh07", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DataModel.FK_fds01_hh07", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("DataModel.FK_fds01_hh07", "Employee", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="DocRecord")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DocRecord : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DocRecord object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static DocRecord CreateDocRecord(global::System.Int32 id)
        {
            DocRecord docRecord = new DocRecord();
            docRecord.Id = id;
            return docRecord;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UpRecordId
        {
            get
            {
                return _UpRecordId;
            }
            set
            {
                OnUpRecordIdChanging(value);
                ReportPropertyChanging("UpRecordId");
                _UpRecordId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpRecordId");
                OnUpRecordIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UpRecordId;
        partial void OnUpRecordIdChanging(Nullable<global::System.Int32> value);
        partial void OnUpRecordIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DocId
        {
            get
            {
                return _DocId;
            }
            set
            {
                OnDocIdChanging(value);
                ReportPropertyChanging("DocId");
                _DocId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DocId");
                OnDocIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DocId;
        partial void OnDocIdChanging(Nullable<global::System.Int32> value);
        partial void OnDocIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ContragentId
        {
            get
            {
                return _ContragentId;
            }
            set
            {
                OnContragentIdChanging(value);
                ReportPropertyChanging("ContragentId");
                _ContragentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContragentId");
                OnContragentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ContragentId;
        partial void OnContragentIdChanging(Nullable<global::System.Int32> value);
        partial void OnContragentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EmployeeId
        {
            get
            {
                return _EmployeeId;
            }
            set
            {
                OnEmployeeIdChanging(value);
                ReportPropertyChanging("EmployeeId");
                _EmployeeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmployeeId");
                OnEmployeeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _EmployeeId;
        partial void OnEmployeeIdChanging(Nullable<global::System.Int32> value);
        partial void OnEmployeeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DueDate
        {
            get
            {
                return _DueDate;
            }
            set
            {
                OnDueDateChanging(value);
                ReportPropertyChanging("DueDate");
                _DueDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DueDate");
                OnDueDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _DueDate;
        partial void OnDueDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDueDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CloseDate
        {
            get
            {
                return _CloseDate;
            }
            set
            {
                OnCloseDateChanging(value);
                ReportPropertyChanging("CloseDate");
                _CloseDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CloseDate");
                OnCloseDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CloseDate;
        partial void OnCloseDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCloseDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CloseType
        {
            get
            {
                return _CloseType;
            }
            set
            {
                OnCloseTypeChanging(value);
                ReportPropertyChanging("CloseType");
                _CloseType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CloseType");
                OnCloseTypeChanged();
            }
        }
        private Nullable<global::System.Decimal> _CloseType;
        partial void OnCloseTypeChanging(Nullable<global::System.Decimal> value);
        partial void OnCloseTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_fss011_fds01", "fds01")]
        public Doc Doc
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Doc>("DataModel.FK_fss011_fds01", "fds01").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Doc>("DataModel.FK_fss011_fds01", "fds01").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Doc> DocReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Doc>("DataModel.FK_fss011_fds01", "fds01");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Doc>("DataModel.FK_fss011_fds01", "fds01", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_fds0111_fss011", "fds0111")]
        public EntityCollection<DocRecordPhase> RecordPhase
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DocRecordPhase>("DataModel.FK_fds0111_fss011", "fds0111");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DocRecordPhase>("DataModel.FK_fds0111_fss011", "fds0111", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_fss011_fss011", "fss0111")]
        public EntityCollection<DocRecord> DownRecord
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DocRecord>("DataModel.FK_fss011_fss011", "fss0111");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DocRecord>("DataModel.FK_fss011_fss011", "fss0111", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_fss011_fss011", "fss011")]
        public DocRecord UpRecord
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DocRecord>("DataModel.FK_fss011_fss011", "fss011").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DocRecord>("DataModel.FK_fss011_fss011", "fss011").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DocRecord> UpRecordReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DocRecord>("DataModel.FK_fss011_fss011", "fss011");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DocRecord>("DataModel.FK_fss011_fss011", "fss011", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_fss011_hh07", "hh07")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DataModel.FK_fss011_hh07", "hh07").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DataModel.FK_fss011_hh07", "hh07").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DataModel.FK_fss011_hh07", "hh07");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("DataModel.FK_fss011_hh07", "hh07", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_fss011_hh15", "hh15")]
        public Contragent Contragent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contragent>("DataModel.FK_fss011_hh15", "hh15").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contragent>("DataModel.FK_fss011_hh15", "hh15").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Contragent> ContragentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contragent>("DataModel.FK_fss011_hh15", "hh15");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Contragent>("DataModel.FK_fss011_hh15", "hh15", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="DocRecordPhase")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DocRecordPhase : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DocRecordPhase object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static DocRecordPhase CreateDocRecordPhase(global::System.Int32 id)
        {
            DocRecordPhase docRecordPhase = new DocRecordPhase();
            docRecordPhase.Id = id;
            return docRecordPhase;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DocRecordId
        {
            get
            {
                return _DocRecordId;
            }
            set
            {
                OnDocRecordIdChanging(value);
                ReportPropertyChanging("DocRecordId");
                _DocRecordId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DocRecordId");
                OnDocRecordIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DocRecordId;
        partial void OnDocRecordIdChanging(Nullable<global::System.Int32> value);
        partial void OnDocRecordIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ContragentId
        {
            get
            {
                return _ContragentId;
            }
            set
            {
                OnContragentIdChanging(value);
                ReportPropertyChanging("ContragentId");
                _ContragentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContragentId");
                OnContragentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ContragentId;
        partial void OnContragentIdChanging(Nullable<global::System.Int32> value);
        partial void OnContragentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhaseDescription
        {
            get
            {
                return _PhaseDescription;
            }
            set
            {
                OnPhaseDescriptionChanging(value);
                ReportPropertyChanging("PhaseDescription");
                _PhaseDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhaseDescription");
                OnPhaseDescriptionChanged();
            }
        }
        private global::System.String _PhaseDescription;
        partial void OnPhaseDescriptionChanging(global::System.String value);
        partial void OnPhaseDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartDate;
        partial void OnStartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private global::System.String _EndDate;
        partial void OnEndDateChanging(global::System.String value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UpPhaseId
        {
            get
            {
                return _UpPhaseId;
            }
            set
            {
                OnUpPhaseIdChanging(value);
                ReportPropertyChanging("UpPhaseId");
                _UpPhaseId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpPhaseId");
                OnUpPhaseIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UpPhaseId;
        partial void OnUpPhaseIdChanging(Nullable<global::System.Int32> value);
        partial void OnUpPhaseIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_fds0111_fds0111", "fds01111")]
        public EntityCollection<DocRecordPhase> DownPhase
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DocRecordPhase>("DataModel.FK_fds0111_fds0111", "fds01111");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DocRecordPhase>("DataModel.FK_fds0111_fds0111", "fds01111", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_fds0111_fds0111", "fds0111")]
        public DocRecordPhase UpPhase
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DocRecordPhase>("DataModel.FK_fds0111_fds0111", "fds0111").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DocRecordPhase>("DataModel.FK_fds0111_fds0111", "fds0111").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DocRecordPhase> UpPhaseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DocRecordPhase>("DataModel.FK_fds0111_fds0111", "fds0111");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DocRecordPhase>("DataModel.FK_fds0111_fds0111", "fds0111", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_fds0111_fss011", "fss011")]
        public DocRecord DocRecord
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DocRecord>("DataModel.FK_fds0111_fss011", "fss011").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DocRecord>("DataModel.FK_fds0111_fss011", "fss011").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DocRecord> DocRecordReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DocRecord>("DataModel.FK_fds0111_fss011", "fss011");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DocRecord>("DataModel.FK_fds0111_fss011", "fss011", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_fds0111_hh15", "hh15")]
        public Contragent Contragent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contragent>("DataModel.FK_fds0111_hh15", "hh15").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contragent>("DataModel.FK_fds0111_hh15", "hh15").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Contragent> ContragentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contragent>("DataModel.FK_fds0111_hh15", "hh15");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Contragent>("DataModel.FK_fds0111_hh15", "hh15", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="contraent">Initial value of the Contraent property.</param>
        public static Employee CreateEmployee(global::System.Int32 id, global::System.Int32 contraent)
        {
            Employee employee = new Employee();
            employee.Id = id;
            employee.Contraent = contraent;
            return employee;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Contraent
        {
            get
            {
                return _Contraent;
            }
            set
            {
                OnContraentChanging(value);
                ReportPropertyChanging("Contraent");
                _Contraent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Contraent");
                OnContraentChanged();
            }
        }
        private global::System.Int32 _Contraent;
        partial void OnContraentChanging(global::System.Int32 value);
        partial void OnContraentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SureName
        {
            get
            {
                return _SureName;
            }
            set
            {
                OnSureNameChanging(value);
                ReportPropertyChanging("SureName");
                _SureName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SureName");
                OnSureNameChanged();
            }
        }
        private global::System.String _SureName;
        partial void OnSureNameChanging(global::System.String value);
        partial void OnSureNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_fss011_hh07", "fss011")]
        public EntityCollection<DocRecord> DocReords
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DocRecord>("DataModel.FK_fss011_hh07", "fss011");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DocRecord>("DataModel.FK_fss011_hh07", "fss011", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_hh07_hh15", "hh15")]
        public Contragent Contragent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contragent>("DataModel.FK_hh07_hh15", "hh15").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contragent>("DataModel.FK_hh07_hh15", "hh15").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Contragent> ContragentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contragent>("DataModel.FK_hh07_hh15", "hh15");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Contragent>("DataModel.FK_hh07_hh15", "hh15", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_fds01_hh07", "fds01")]
        public EntityCollection<Doc> Docs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Doc>("DataModel.FK_fds01_hh07", "fds01");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Doc>("DataModel.FK_fds01_hh07", "fds01", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
