//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DataModel
{
    public partial class DocRecord
    {
        public DocRecord()
        {
            this.RecordPhase = new HashSet<DocRecordPhase>();
            this.DownRecord = new HashSet<DocRecord>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UpRecordId { get; set; }
        public Nullable<int> DocId { get; set; }
        public Nullable<int> ContragentId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<decimal> CloseType { get; set; }
        public string Description { get; set; }
    
        public virtual Doc Doc { get; set; }
        public virtual ICollection<DocRecordPhase> RecordPhase { get; set; }
        public virtual ICollection<DocRecord> DownRecord { get; set; }
        public virtual DocRecord UpRecord { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Contragent Contragent { get; set; }
    }
    
}
