//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace DataModel
{
    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Doc> Docs { get; set; }
        public DbSet<DocRecordPhase> DocRecordPhases { get; set; }
        public DbSet<DocRecord> DocRecords { get; set; }
        public DbSet<Employee> Employes { get; set; }
        public DbSet<Contragent> Contragents { get; set; }
    }
}
